#!/usr/bin/env python3
"""Generate the two opt-in Folderstorm themes. Requires Pillow >= 10.1 for authoring.

The viewer ships the generated XML/PNG files; it never runs this script.
Textures use inherited filenames and dimensions to retain existing nine-slice
metrics. No existing texture pixels are used or modified.
"""

from pathlib import Path
import xml.etree.ElementTree as ET

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
SKINS = ROOT / "indra/newview/skins"
THEMES = {
    "folderstorm": dict(
        name="Folderstorm Violet", bg="#111016", panel="#1a1921",
        line="#302d3b", text="#f5f3fa", muted="#ada9ba", accent="#bfa4fc",
        bright="#9f74f2", gold="#f0cc53", title="#302140",
        selected="#51347d", inventory="#51347d", hover="#352943",
        input="#111016", ink="#211332", frame="#735595",
    ),
    "electric_jungle": dict(
        name="Electric Jungle", bg="#100a19", panel="#1c112b",
        line="#69408b", text="#f4f3fc", muted="#c3b4d4", accent="#13eff5",
        bright="#a56bff", gold="#b0ff26", title="#ac008f",
        selected="#622792", inventory="#32491e", hover="#352344",
        input="#100a19", ink="#100a19", frame="#ff00db",
    ),
}


def rgb(value):
    return tuple(int(value[i:i + 2], 16) for i in (1, 3, 5))


def color_value(value, alpha=1):
    return " ".join(f"{v / 255:.6f}" for v in rgb(value)) + f" {alpha:g}"


def write_colors(folder, p):
    root = ET.Element("colors")
    root.append(ET.Comment("Generated by scripts/skins/generate_folderstorm_themes.py"))
    for name in ("bg", "panel", "line", "text", "muted", "accent", "bright", "gold",
                 "title", "selected", "inventory", "hover", "input", "ink", "frame"):
        ET.SubElement(root, "color", name="Theme" + name.title(), value=color_value(p[name]))
    roles = {
        "text": "TextFgColor TextFgReadOnlyColor TextDefaultColor TextCursorColor "
                "TextEmbeddedItemColor LabelTextColor ButtonLabelColor ButtonLabelSelectedColor "
                "LabelSelectedColor MenuItemEnabledColor InventoryItemEnabledColor "
                "InventoryItemHighlightFgColor InventoryItemLibraryColor ChatHistoryTextColor "
                "AccordionHeaderTextColor NotifyTextColor ToolTipTextColor InspectorTipTextColor "
                "ScriptEditorTextRColor NotecardTextColor",
        "muted": "TextFgTentativeColor InventoryItemSuffixColor LabelDisabledColor "
                 "LabelSelectedDisabledColor ButtonLabelDisabledColor ButtonLabelSelectedDisabledColor "
                 "MenuItemDisabledColor ScrollDisabledColor TimeTextColor",
        "panel": "DkGray DkGray2 SL-Background SL-Background_Light MenuDefaultBgColor "
                 "MenuPopupBgColor ComboListBgColor BackgroundChatColor FSChatHistoryBackground "
                 "ChatHistoryBgColor AlertBoxColor NotifyBoxColor ToolTipBgColor "
                 "TextBgReadOnlyColor MouseGray BottomTrayOpaqueColor BottomTrayAlphaColor",
        "bg": "MenuBarBgColor ConsoleBackground",
        "input": "TextBgFocusColor TextBgWriteableColor ScriptEditorTextBgRColor "
                 "NotecardBackgroundColor FilterBackgroundColor lineeditor_preedit_bg",
        "selected": "ScrollSelectedBGColor MenuItemHighlightBgColor SysWellItemSelected "
                    "OutfitGalleryItemSelected OutfitGalleryItemWorn HighlightPanelBackground "
                    "simpleeditor_bg_selected NotecardSelectionColor",
        "inventory": "InventoryItemHighlightBgColor",
        "accent": "AccentColor FolderstormAccent FocusColor EmphasisColorLight SchemeLightest "
                  "InventorySearchStatusColor InventoryFocusOutlineColor InventoryItemLinkColor "
                  "HTMLLinkColor HTMLLinkColorHovertips FilterTextColor FolderViewLoadingMessageTextColor "
                  "TextEmbeddedItemReadOnlyColor ToolTipBorderColor NotecardCursorColor",
        "bright": "EmphasisColor ButtonColor lineeditor_highlight SliderThumbCenterColor "
                  "SelectedOutfitTextColor ChatToastAgentNameColor ToolbarDropZoneColor",
        "gold": "InventoryFavoriteColor ButtonFlashBgColor",
        "line": "ColorSwatchBorderColor FloaterUnfocusBorderColor",
        "frame": "FloaterFocusBorderColor",
        "hover": "ScrollHoveredColor TextBgHighlightColor",
    }
    for source, names in roles.items():
        for name in names.split():
            ET.SubElement(root, "color", name=name, reference="Theme" + source.title())
    # Colored frame PNGs must not be multiplied by the grey base skin tint.
    for name in ("floater_bg_color", "floater_bg_color_a", "ButtonImageColor", "FloaterButtonImageColor"):
        ET.SubElement(root, "color", name=name, reference="White")
    for name in ("ScrollUnselectedColor", "ScrollSelectedFGColor", "MenuItemHighlightFgColor"):
        ET.SubElement(root, "color", name=name, reference="ThemeText")
    if folder == "electric_jungle":
        # Lists/menus support a separate selected foreground; Inventory links
        # and library entries do not, so Inventory keeps a dark green fill.
        for name in ("ScrollSelectedBGColor", "MenuItemHighlightBgColor"):
            next(c for c in root if c.get("name") == name).set("reference", "ThemeGold")
        for name in ("ScrollSelectedFGColor", "MenuItemHighlightFgColor"):
            next(c for c in root if c.get("name") == name).set("reference", "ThemeInk")
    for name, source, alpha in (("EmphasisColor_13", "accent", .13),
                                ("EmphasisColor_35", "accent", .35),
                                ("SchemeLightest_35", "accent", .35),
                                ("DefaultHighlightLight", "accent", .25),
                                ("DefaultHighlightDark", "accent", .10)):
        ET.SubElement(root, "color", name=name, value=color_value(p[source], alpha))
    ET.indent(root, space="  ")
    dest = SKINS / "firestorm/themes" / folder / "colors.xml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text('<?xml version="1.0" encoding="utf-8"?>\n' + ET.tostring(root, encoding="unicode") + "\n")


def texture_paths():
    """Limit overrides to chrome, leaving status/parcel/Inventory icons alone."""
    prefixes = ("PushButton_", "DropDown_", "ComboButton_", "SegmentedBtn_",
                "TabTop_", "TabLeft_", "Toolbar_", "TextField_", "ScrollThumb_",
                "ScrollTrack_", "SliderTrack_", "SliderThumb_", "Progress", "NavBar_BG",
                "Window_", "Accordion_", "Checkbox_", "RadioButton_")
    extras = {"Tooltip", "Inspector_Background", "Volume_Background",
              "TimeBasedMediaBackground", "BottomTray_BG", "bevel_background"}
    paths = set()
    for skin in ("default", "firestorm"):
        for t in ET.parse(SKINS / skin / "textures/textures.xml").getroot():
            file = t.get("file_name", "")
            stem = Path(file).stem
            chrome = file.startswith(("widgets/", "containers/", "windows/", "navbar/", "bottomtray/"))
            if chrome and file.endswith(".png") and (stem.startswith(prefixes) or stem in extras):
                if not any(x in stem for x in ("Arrow", "Transparent", "Login", "Sign")):
                    paths.add(file)
    return sorted(paths)


def draw_texture(file, size, p, wild):
    w, h = size
    stem = Path(file).stem
    im = Image.new("RGBA", size)
    d = ImageDraw.Draw(im)
    disabled = "Disabled" in stem
    selected = any(x in stem for x in ("Selected", "_On", "_Press", "_Flash"))
    over = any(x in stem for x in ("Over", "Active", "Highlight"))
    fill = p["selected"] if selected else p["hover"] if over else p["panel"]
    edge = p["line"] if disabled else p["accent"] if selected or over else p["line"]
    radius = 1 if wild else 3
    if stem.startswith(("Checkbox_", "RadioButton_")):
        ink = p["muted"] if disabled else p["gold"] if wild else p["accent"]
        box = (1, 1, w - 2, h - 2)
        if stem.startswith("RadioButton_"):
            d.ellipse(box, fill=p["input"], outline=edge)
            if "_On" in stem:
                d.ellipse((w // 2 - 2, h // 2 - 2, w // 2 + 2, h // 2 + 2), fill=ink)
        else:
            d.rounded_rectangle(box, radius=1, fill=p["input"], outline=edge)
            if "_On" in stem:
                d.line(((3, h // 2), (w // 2 - 1, h - 4), (w - 4, 3)), fill=ink, width=2)
    elif stem.startswith("Window_"):
        edge = p["frame"] if "Foreground" in stem else p["line"]
        d.rounded_rectangle((0, 0, w - 1, h - 1), radius=radius, fill=p["panel"], outline=edge)
        if "NoTitle" not in stem:
            # The inherited upper fixed slice is 36 pixels high. Keep the
            # 25-pixel header in it so resizing cannot stretch its title.
            d.rectangle((1, 1, w - 2, 24), fill=p["title"])
            d.line((1, 25, w - 2, 25), fill=edge)
            if wild:
                # Window textures stretch columns 4..25. Even a two-pixel
                # diagonal can bleed into that center and across title text.
                # Keep the pattern strictly within the four-pixel edge slices.
                for y in range(2, 24, 6):
                    d.line((1, y, 2, y + 2), fill=p["accent"], width=1)
                    d.line((w - 3, y, w - 2, y + 2), fill=p["gold"], width=1)
    elif stem.startswith("TextField_"):
        d.rectangle((0, 0, w - 1, h - 1), fill=p["panel"] if disabled else p["input"], outline=edge)
    elif stem.startswith(("NavBar_BG", "BottomTray_BG")):
        d.rectangle((0, 0, w - 1, h - 1), fill=p["bg"])
        d.line((0, h - 1, w - 1, h - 1), fill=p["frame"] if wild else p["line"])
    elif stem.startswith(("SliderTrack_", "ScrollTrack_")):
        d.rounded_rectangle((0, 0, w - 1, h - 1), radius=1, fill=p["bg"], outline=p["line"])
    elif stem.startswith(("ScrollThumb_", "SliderThumb_", "ProgressBar")):
        fill = p["muted"] if disabled else p["bright"]
        d.rounded_rectangle((0, 0, w - 1, h - 1), radius=radius, fill=fill, outline=edge)
    else:
        d.rounded_rectangle((0, 0, w - 1, h - 1), radius=radius, fill=fill, outline=edge)
        if wild and selected:
            d.line((3, h - 2, w - 4, h - 2), fill=p["gold"])
    if stem.startswith(("DropDown_", "ComboButton_")):
        # Dropdown arrows live inside the fixed right slice.
        x = w - 7 if stem.startswith("DropDown_") else w // 2
        y = h // 2
        ink = p["muted"] if disabled else p["text"]
        up = "Up" in stem
        d.polygon(((x - 3, y + (2 if up else -1)),
                   (x + 3, y + (2 if up else -1)),
                   (x, y + (-1 if up else 2))), fill=ink)
    return im


def write_textures(folder, p):
    dest = SKINS / "firestorm/themes" / folder / "textures"
    for file in texture_paths():
        original = SKINS / "firestorm/textures" / file
        if not original.exists():
            original = SKINS / "default/textures" / file
        with Image.open(original) as source:
            im = draw_texture(file, source.size, p, folder == "electric_jungle")
        path = dest / file
        path.parent.mkdir(parents=True, exist_ok=True)
        im.save(path, optimize=True)


def write_preview(folder, p):
    """An explicitly illustrative widget sample for the Skins selector."""
    im = Image.new("RGB", (900, 560), p["bg"])
    d = ImageDraw.Draw(im)
    # Pillow's bundled font keeps regeneration independent of OS fonts.
    font = ImageFont.load_default(size=18)
    small = ImageFont.load_default(size=15)
    d.text((24, 16), p["name"] + "  /  UI sample", fill=p["text"], font=font)
    for x, name in zip((24, 106, 177, 256, 324, 404), ("Avatar", "Comm", "World", "Build", "Content", "Help")):
        d.text((x, 54), name, fill=p["text"], font=small)
    d.rectangle((24, 86, 875, 118), fill=p["panel"], outline=p["line"])
    d.text((38, 94), "Boardwalk    Cafe     |    Driving    Inventory sorting", fill=p["accent"], font=small)
    for x, y, w, h, title in ((24, 140, 393, 340, "Inventory"), (453, 140, 422, 282, "Workspaces")):
        # Show the same authored window design, with a full-size title band.
        d.rounded_rectangle((x, y, x + w, y + h), radius=3, fill=p["panel"], outline=p["frame"])
        d.rectangle((x + 1, y + 1, x + w - 1, y + 29), fill=p["title"])
        if folder == "electric_jungle":
            for offset in range(2, 24, 6):
                d.line((x + 1, y + offset, x + 3, y + offset + 2), fill=p["accent"], width=2)
                d.line((x + w - 3, y + offset, x + w - 1, y + offset + 2), fill=p["gold"], width=2)
        d.text((x + 12, y + 5), title, fill=p["text"], font=font)
    for i, name in enumerate(("My Inventory", "   Clothing", "      Casual", "      Formal", "      Shoes", "   Objects", "   Textures", "   Landmarks")):
        y = 202 + 32 * i
        if i == 1:
            d.rectangle((34, y - 3, 407, y + 24), fill=p["inventory"])
        d.text((44, y), name, fill=p["text"], font=small)
    for i, name in enumerate(("Driving", "Inventory sorting", "Photography")):
        y = 202 + 38 * i
        fill = (p["gold"] if folder == "electric_jungle" else p["selected"]) if i == 1 else p["bg"]
        ink = p["ink"] if i == 1 and folder == "electric_jungle" else p["text"]
        d.rectangle((467, y - 6, 860, y + 25), fill=fill, outline=p["line"])
        d.text((479, y), name, fill=ink, font=small)
    for x, label in ((468, "Apply"), (660, "Save current")):
        d.rounded_rectangle((x, 335, x + 178, 370), radius=3, fill=p["selected"], outline=p["accent"])
        d.text((x + 18, 345), label, fill=p["text"], font=small)
    d.text((468, 389), "Previous arrangement", fill=p["accent"], font=small)
    d.line((24, 506, 875, 506), fill=p["line"])
    d.text((24, 525), "Chat      Inventory      Map      Camera      Workspaces", fill=p["text"], font=small)
    for i, key in enumerate(("bg", "panel", "accent", "bright", "gold")):
        d.rectangle((675 + 40 * i, 520, 703 + 40 * i, 545), fill=p[key])
    path = SKINS / "default/textures/skinspreview" / (folder + ".png")
    im.save(path, optimize=True)


if __name__ == "__main__":
    for folder, palette in THEMES.items():
        write_colors(folder, palette)
        write_textures(folder, palette)
        write_preview(folder, palette)
    print(f"Generated {len(THEMES)} themes, {len(texture_paths())} chrome textures each, and selector previews.")
